
language: java
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - terrasan111@yandex.ru
    on_success: never 
    on_failure: always 
    